"""change pin string type size

Revision ID: 38de0da78b82
Revises: 18e2379324f4
Create Date: 2024-11-14 20:26:39.916194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38de0da78b82'
down_revision = '18e2379324f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pin',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pin',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
