"""update nullable on overall review

Revision ID: ea060501f823
Revises: 38de0da78b82
Create Date: 2024-11-18 18:52:00.151686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea060501f823'
down_revision = '38de0da78b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overall_review', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('review_status',
               existing_type=mysql.ENUM('pending', 'completed', 'canceled'),
               nullable=False)
        batch_op.alter_column('review_body',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overall_review', schema=None) as batch_op:
        batch_op.alter_column('review_body',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('review_status',
               existing_type=mysql.ENUM('pending', 'completed', 'canceled'),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
